version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Building the front end"
      # - npm install
      # - npm run build
  post-build:
    commands:
      - echo "Deploying artefacts to frontend bucket"
      - aws s3 sync s3://cloudpipeline/P2 ./
      - aws s3 sync ./ s3://coms6998-hw2-jw4202-frontend

      